### PR TITLE
Add temporary home page

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR adds a `home` app where the homepage will live, and its url routings.

### Demo

screen shot 2018-08-12 at 10 23 18

## Testing Instructions

1. Spin up the webserver cluster:
```
# To run the cluster up
docker-compose -f infra/docker_dev/docker-compose.yml -p smarty_recipe up
```
2. Open up web browser and go to [http://localhost:8000/](http://localhost:8000/)

### CODE REVIEW

**Comment by map34** [comment]
Oyy do we want to use server side or client side rendering here? Was thinking of using React as a client-rendered frontend, let me know what you think!

**Comment by map34** [comment]
Also linting errors bruh haha

**Comment by lsetiawan** [comment]
> Also linting errors bruh haha

Fixing that haha.. your linter is very picky xD

**Comment by lsetiawan** [comment]
> Oyy do we want to use server side or client side rendering here? Was thinking of using React as a client-rendered frontend, let me know what you think!

React is fine. We can do client side rendering. This is just a temporary placeholder.

Lemme get this straight, so Django is just used to serialize the info aka the REST API for the React App?

**Comment by map34** [comment]
> React is fine. We can do client side rendering. This is just a temporary placeholder.

> Lemme get this straight, so Django is just used to serialize the info aka the REST API for the React App?

@lsetiawan 

Yes, so we can serve the React app through a CDN somewhere, then the frontend will request the resources as necessary using AJAX. So two things: the View routings will then be set by React on the frontend, then the model/controller routings will be set by Django.

That way, if we have multiple frontend clients (React, ReactNative, Electron Desktop App, etc), we can just get the necessary resources through our Django API.

@scaraclette @dwinasolihin FYI ^

**Comment by map34** [comment]
Looks good tho! Merging this for now @lsetiawan

**Pull request merged**
