### PR TITLE
Initial SmartyRecipe's Django development

### PR DESCRIPTION
**Pull request by map34**
## Overview

The main web development repo for the SmartyRecipe + OceanHub merge.

## Demo

* Webserver + PostgreSQL
```bash
16:59 $ docker-compose -f infra/docker_dev/docker-compose.yml -p smarty_recipe up
Starting smarty_recipe_postgresdb_1 ... done
Starting smarty_recipe_webserver_1  ... done
Attaching to smarty_recipe_postgresdb_1, smarty_recipe_webserver_1
postgresdb_1  | 2018-08-11 23:59:59.555 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresdb_1  | 2018-08-11 23:59:59.555 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgresdb_1  | 2018-08-11 23:59:59.561 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresdb_1  | 2018-08-11 23:59:59.578 UTC [25] LOG:  database system was shut down at 2018-08-11 22:49:41 UTC
postgresdb_1  | 2018-08-11 23:59:59.592 UTC [1] LOG:  database system is ready to accept connections
webserver_1   |                                  List of databases
webserver_1   |    Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
webserver_1   | -----------+----------+----------+------------+------------+-----------------------
webserver_1   |  postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
webserver_1   |  template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
webserver_1   |            |          |          |            |            | postgres=CTc/postgres
webserver_1   |  template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
webserver_1   |            |          |          |            |            | postgres=CTc/postgres
webserver_1   | (3 rows)
webserver_1   |
webserver_1   | 20180812t000000 Postgres is up - executing command
```

* Jupyter Hub
screen shot 2018-08-11 at 5 01 43 pm

## Testing Instructions

 * Follow README.md

### CODE REVIEW

**Comment by scaraclette** [comment]
Cool bruh! Don't know most of the things here but looks legit

**Comment by dwinasolihin** [comment]
I think it looks good! Shall I merge?

**Comment by lsetiawan** [comment]
You took my job! lol Looks great bro! 👍

**Comment by map34** [comment]
@scaraclette @dwinasolihin we can go over it on Tuesday, fortunately the frontend is bare enough we can just use the existing repo

**Comment by map34** [comment]
@lsetiawan sowwy haha, this is what happens if I get too much time on my hand. Let me know if we need to add more things to here.

**Pull request merged**
